### ISSUE TITLE
How to get it running?

### ISSUE THREAD

**Issue by Endebert** [reTHINK-project/dev-runtime-browser#40]
Hi guys,

I'm trying to get the demo working (in the end I want my own hyperty to be loaded), but it seems to fail on start and I don't know why.

Here is the log, if anyone can help, it would be greatly appreciated: [localhost-1461597484886.txt](https://github.com/reTHINK-project/dev-runtime-browser/files/234846/localhost-1461597484886.txt)

I think this is related to this issue: https://github.com/reTHINK-project/dev-runtime-core/issues/82 but I'm not sure.

**Comment by dvilchez** [comment]
@Endebert the problem is the connection with the msg node:
WebSocket connection to 'wss://msg-node.localhost:9090/ws' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
loginWithRP
Uncaught (in promise) Response timeout!

I guess connection has been refused because the certificate. Try to load https://msg-node.localhost:9090 in your browser and accept the certificate.

**Comment by Endebert** [comment]
Loading https://msg-node.localhost:9090/ also returns `ERR_CONNECTION_REFUSED`, but it doesn't seem to be related to certificates.

**Comment by dvilchez** [comment]
Do you have a local msg-node running?

**Comment by Endebert** [comment]
No, do I need to have one running?

**Comment by dvilchez** [comment]
Yes, https://github.com/reTHINK-project/dev-runtime-browser/blob/master/startup_guide.md

**Comment by Endebert** [comment]
Unfortunately, I can't get far with the startup guide either.

I created a small website in dev-runtime-browser/ren_test:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script src="https://rethink-app.quobis.com/.well-known/runtime/rethink.js"
            ></script>
</head>
<body>
<script>
    let domain = "rethink-app.quobis.com";
    let successFunc = function () {
        console.log("something happened!");
    };
    let runtimeLoader = window.rethink.default.install(domain).then(successFunc);
</script>
</body>
</html>
```
I run it using `http-server --cors -S -p 443 -C rethink-certificate.cert -K rethink-certificate.key ren_test/` 

If I run it like this, it fails because `window.rethink.default` is undefined. After changing it to just `let runtimeLoader = window.rethink.install(domain).then(successFunc);` I get the following errors:

1. `Uncaught TypeError: window.rethink.install(...).then is not a function`
2. `Uncaught SecurityError: Blocked a frame with origin "https://rethink-app.quobis.com" from accessing a frame with origin "https://localhost". Protocols, domains, and ports must match.`

**Comment by dvilchez** [comment]
It looks like something related with SOP. In the meanwhile, Could you try with the second scenario described in the guide?

**Comment by Endebert** [comment]
I can't try the second scenario because I don't have access to the dev-registry-browser repository.

I tried getting the third scenario running but that needs the resources from dev-registry-browser, too.

**Comment by dvilchez** [comment]
Sorry @Endebert, it was an error on the documentation, the right repo is dev-runtime-browser. I fixed it yet.

**Comment by Endebert** [comment]
Ok, I'm not sure if I'm doing this right but i copied the folder /example/resources to the root folder and tried it again. I'm still getting errors, it seems the msg node doesn't accept the connection: [localhost-1461756658482.txt](https://github.com/reTHINK-project/dev-runtime-browser/files/238535/localhost-1461756658482.txt)

**Comment by Endebert** [comment]
Since the provided example seems to work (kind of), I'm trying to get my little website running, but it doesn't work still. This is the current state of it:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <script src="https://localhost/.well-known/runtime/rethink.js"></script>
</head>
<body>
<script>
    let domain = "localhost";
    let successFunc = function () {
        console.log("something happened!");
    };
    let runtimeLoader = window.rethink.install(domain).then(successFunc);
</script>
</body>
</html>
```

I copied over the folders ".well-known"  and "resources" to the website folder. But when accessing the website, the console only contains: `Uncaught TypeError: window.rethink.install is not a function`

So it loaded rethink.js, but something seems to fail because window.rethink.install is undefined.

**Comment by dvilchez** [comment]
Sorry, another mismatch on the documentation:

rethink.default.install({"domain": domain, development: true})

if you set development to true RuntimeCatalogue-Local will be used

**Comment by Endebert** [comment]
Thanks, @dvilchez, that seemed to have solved it. 

But it looks like I'm unable to deploy a hyperty. I created a hyperty in /resources/descriptor/Hyperties.json but when I try to deploy it with runtime.requireHyperty() I get the error with msg.node again.

Here is the log: [localhost-1461935992378.txt](https://github.com/reTHINK-project/dev-runtime-browser/files/242507/localhost-1461935992378.txt)

Is there anyway to get around that? Do I really have to have my own msg node when I do it like this? As you can see in the log, all the hyperty is supposed to do is create an alert dialogue, what is the simplest way to get this executed? Also why do I have to log in with google and in the end have two browser windows with the same website?

**Comment by dvilchez** [comment]
Sorry @Endebert, I can't answer that question, as far as I know a hyperty is associated with an identity and get this identity is mandatory.

**Comment by Endebert** [comment]
OK but what about the problem with the msg node? Is there any way I can configure the runtime to use an external msg node or something? It does work with a local msg node, but the first scenario in the startup guide never mentions the need of a local msg node

**Comment by dvilchez** [comment]
Yes, yo have to change it in protostub descriptor

https://github.com/reTHINK-project/dev-runtime-browser/blob/master/example/resources/descriptors/ProtoStubs.json#L19

**Comment by Endebert** [comment]
I changed the url to wss://msg-node.hybroker.rethink.ptinovacao.pt/ws, and there seems to be no error, but the hyperty is not being executed: [localhost-1461939637038.txt](https://github.com/reTHINK-project/dev-runtime-browser/files/242618/localhost-1461939637038.txt)

As you can see in the log, I want to execute: `console.log('it worked!'); alert('it worked!');`

**Comment by dvilchez** [comment]
Please check if Protostub descriptor loaded by your browser has the right URL, maybe it is cached

**Comment by Endebert** [comment]
I double-checked, the protostub descriptor has the right URL

**Comment by dvilchez** [comment]
Could you unfold this on your console log?

    2. return the ProtoStub descriptor: t {_guid: 1, _type: "protostub", _version: "0.1", _objectName: "VertxProtoStub", _description: "Description of VertxProtoStub"…}

**Comment by Endebert** [comment]
That's what I did to double-check, but here is the log: [localhost-1461941112590.txt](https://github.com/reTHINK-project/dev-runtime-browser/files/242649/localhost-1461941112590.txt)

**Comment by dvilchez** [comment]
@Endebert it looks like the last changes in runtime and runtime-browser made invalid the process described on startup guide. Let me check again every scenario and fix the guide.

**Comment by aoncorici** [comment]
seems the right way to create a Hyperty is to use the https://github.com/reTHINK-project/dev-hyperty-toolkit repository. 

Still to be discussed tomorrow what is the relation to the dev-runtime-browser to make it running for real.

**Comment by dvilchez** [comment]
Yes, the right way to create Hyperties is described on  https://github.com/reTHINK-project/dev-hyperty-toolkit repo.

BTW I updated startup guide and changed the first example to match with scenario one, the second example and hello example match with scenario two.

**Comment by Endebert** [comment]
Since dev-hyperty-toolkit is supposed to be used, I guess this can be closed
